export const SPECIES_PROFILES = Object.freeze({
  ant: {
    label: '개미형',
    pattern: 'zigzag',
    personality: 'active',
    speed: 0.9,
    drift: 1.15,
    fleeChance: 0.65,
    fleeDistance: 0.7,
    signalRange: 0.85,
    signalChance: 0.8,
  },
  cabbage: {
    label: '나비형',
    pattern: 'flutter',
    personality: 'curious',
    speed: 1.0,
    drift: 1.15,
    fleeChance: 0.95,
    fleeDistance: 0.9,
    signalRange: 1.0,
    signalChance: 1.0,
  },
  blueband: {
    label: '숲나비형',
    pattern: 'flutter',
    personality: 'timid',
    speed: 1.08,
    drift: 1.2,
    fleeChance: 1.25,
    fleeDistance: 1.05,
    signalRange: 1.1,
    signalChance: 1.1,
  },
  blackyellow: {
    label: '활공나비형',
    pattern: 'flutter',
    personality: 'active',
    speed: 1.12,
    drift: 1.25,
    fleeChance: 1.05,
    fleeDistance: 1.0,
    signalRange: 1.05,
    signalChance: 1.05,
  },
  dragonfly: {
    label: '잠자리형',
    pattern: 'dart',
    personality: 'timid',
    speed: 1.28,
    drift: 1.25,
    fleeChance: 1.35,
    fleeDistance: 1.25,
    signalRange: 1.25,
    signalChance: 1.25,
  },
  diving: {
    label: '수서형',
    pattern: 'walk',
    personality: 'calm',
    speed: 0.82,
    drift: 0.85,
    fleeChance: 0.8,
    fleeDistance: 0.85,
    signalRange: 0.9,
    signalChance: 0.85,
  },
  firefly: {
    label: '발광형',
    pattern: 'glow',
    personality: 'curious',
    speed: 0.9,
    drift: 1.05,
    fleeChance: 0.75,
    fleeDistance: 0.8,
    signalRange: 1.45,
    signalChance: 1.7,
  },
  hornet: {
    label: '말벌형',
    pattern: 'dart',
    personality: 'bold',
    speed: 1.22,
    drift: 1.18,
    fleeChance: 0.5,
    fleeDistance: 0.7,
    signalRange: 1.2,
    signalChance: 1.15,
  },
  waterbug: {
    label: '물장군형',
    pattern: 'walk',
    personality: 'bold',
    speed: 0.9,
    drift: 0.9,
    fleeChance: 0.55,
    fleeDistance: 0.75,
    signalRange: 0.95,
    signalChance: 0.9,
  },
  cricket: {
    label: '도약형',
    pattern: 'jump',
    personality: 'active',
    speed: 1.0,
    drift: 1.1,
    jumpChance: 1.35,
    jumpDistance: 1.25,
    fleeChance: 1.05,
    fleeDistance: 1.1,
    signalRange: 1.0,
    signalChance: 1.05,
  },
});

export const DEFAULT_SPECIES_PROFILE = Object.freeze({
  label: '기본형',
  pattern: null,
  personality: null,
  speed: 1,
  drift: 1,
  jumpChance: 1,
  jumpDistance: 1,
  fleeChance: 1,
  fleeDistance: 1,
  signalRange: 1,
  signalChance: 1,
});

export function getSpeciesProfile(entity = {}) {
  const id = entity.bug?.id || entity.id;
  return SPECIES_PROFILES[id] || DEFAULT_SPECIES_PROFILE;
}

export function applySpeciesContext(entity, ctx = {}) {
  const species = getSpeciesProfile(entity);
  return {
    ...ctx,
    species,
    speciesName: species.label || DEFAULT_SPECIES_PROFILE.label,
  };
}
