const GPS_SETTINGS_KEY='catchabugs.menuSettings.v2';
const GPS_STATE_KEY='catchabugs.gps.v1';
const GPS_MIN_MOVE_M=5;
const GPS_MAX_ACCURACY_M=45;
const GPS_WORLD_SCALE=6;
const GPS_HEADING_OFFSET=0;
const GPS_MAX_STEP_WORLD=42;
function $(s){return document.querySelector(s)}
function safeParse(raw){try{return raw?JSON.parse(raw):null}catch{return null}}
function loadSettings(){return safeParse(localStorage.getItem(GPS_SETTINGS_KEY))||{}}
function saveSettings(settings){localStorage.setItem(GPS_SETTINGS_KEY,JSON.stringify(settings))}
function isMobile(){const ua=navigator.userAgent||'';return /Android|iPhone|iPad|iPod|Mobile/i.test(ua)||(matchMedia('(pointer: coarse)').matches&&innerWidth<=900)}
function toast(message){const node=$('#toast');if(!node)return;node.textContent=message;node.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.style.display='none',1500)}
function saveGps(data){localStorage.setItem(GPS_STATE_KEY,JSON.stringify({...data,updatedAt:new Date().toISOString()}))}
function loadGps(){return safeParse(localStorage.getItem(GPS_STATE_KEY))||{enabled:false,status:'off',totalMove:0}}
function setEnabled(value){const settings=loadSettings();settings.gpsEnabled=!!value;saveSettings(settings)}
function gameApi(){return window.CATCHABUGS_GAME||null}
function player(){return gameApi()?.getPlayer?.()||safeParse(localStorage.getItem('catchabugs.core.v2'))?.player||{x:0,y:0}}
let watchId=null;
let anim=null;
function toRad(v){return Number(v||0)*Math.PI/180}
function metersBetween(a,b){const R=6371000;const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const lat1=toRad(a.lat),lat2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function deltaMeters(a,b){const meanLat=toRad((a.lat+b.lat)/2);return {east:(b.lng-a.lng)*111320*Math.cos(meanLat),north:(b.lat-a.lat)*110540}}
function currentHeading(){const raw=$('#headingText')?.textContent||'';const m=raw.match(/(\d{1,3})°/);if(m)return Number(m[1])||0;return Number(window.CATCHABUGS_RADAR_COMPASS?.getHeading?.()||0)}
function dirLabel(east,north){const deg=(Math.atan2(east,north)*180/Math.PI+360)%360;const names=['N','NE','E','SE','S','SW','W','NW'];return {deg,txt:names[Math.round(deg/45)%8]}}
function rotateByHeading(east,north){const h=toRad(currentHeading()+GPS_HEADING_OFFSET);const cos=Math.cos(h),sin=Math.sin(h);return {east:east*cos+north*sin,north:north*cos-east*sin}}
function injectStyle(){if($('#gpsSystemStyle'))return;const style=document.createElement('style');style.id='gpsSystemStyle';style.textContent=`#gpsHud{position:absolute;left:10px;top:76px;z-index:75;max-width:220px;padding:8px 10px;border-radius:16px;background:#07111ee8;color:white;border:1px solid #9af7ff66;box-shadow:0 10px 24px #0007;font-size:10px;font-weight:1000;line-height:1.35;pointer-events:none}#gpsHud b{display:block;font-size:11px;color:#9af7ff}.gpsPulse{position:absolute;left:50%;top:50%;width:64px;height:64px;border-radius:50%;transform:translate(-50%,-50%);z-index:20;pointer-events:none;border:2px solid #7fffd4;animation:gpsPulse 900ms ease-out forwards}@keyframes gpsPulse{0%{opacity:.95;transform:translate(-50%,-50%) scale(.45)}100%{opacity:0;transform:translate(-50%,-50%) scale(2.2)}}body[data-gps="off"] #gpsHud{display:none}`;document.head.appendChild(style)}
function renderHud(){injectStyle();const gps=loadGps();let hud=$('#gpsHud');if(!gps.enabled||gps.status==='off'){hud?.remove();return}if(!hud){hud=document.createElement('div');hud.id='gpsHud';$('#game')?.appendChild(hud)}const acc=gps.accuracy?`${Math.round(gps.accuracy)}m`:'-';const moved=gps.lastMove?`${gps.lastMove.toFixed(1)}m`:'대기';const total=gps.totalMove?`${gps.totalMove.toFixed(1)}m`:'0m';const dir=gps.dir||'-';const head=Math.round(currentHeading());const chasing=gps.chasing?'추적중':'대기';hud.innerHTML=`<b>📍 탐험모드 ${gps.status==='on'?'ON':'...'}</b>정확도 ${acc} · 방향 ${dir}<br>최근 이동 ${moved} · 누적 ${total}<br>나침반 ${head}° · ${chasing}`}
function pulse(){const game=$('#game');if(!game)return;const p=document.createElement('div');p.className='gpsPulse';game.appendChild(p);setTimeout(()=>p.remove(),950)}
function commitPlayer(x,y,label,final=false){const api=gameApi();if(api?.setPlayer){api.setPlayer(x,y,final?label:'GPS 추적 중','📍');return}const core=safeParse(localStorage.getItem('catchabugs.core.v2'))||{};core.player={...(core.player||{}),x,y,gps:true};localStorage.setItem('catchabugs.core.v2',JSON.stringify(core))}
function stepToward(from,to,maxStep){const dx=to.x-from.x,dy=to.y-from.y;const dist=Math.hypot(dx,dy);if(dist<=maxStep)return {x:to.x,y:to.y,done:true,dist};const r=maxStep/dist;return {x:from.x+dx*r,y:from.y+dy*r,done:false,dist}}
function chaseTarget(target,log){const start=performance.now();let lastTick=0;if(anim)cancelAnimationFrame(anim);function frame(now){const p=player();const next=stepToward({x:Number(p.x||0),y:Number(p.y||0)},target,GPS_MAX_STEP_WORLD);if(now-lastTick>120||next.done){commitPlayer(next.x,next.y,log,next.done);lastTick=now}const gps=loadGps();saveGps({...gps,chasing:!next.done});renderHud();if(!next.done&&now-start<12000)anim=requestAnimationFrame(frame);else{commitPlayer(target.x,target.y,log,true);saveGps({...loadGps(),chasing:false});renderHud()}}anim=requestAnimationFrame(frame)}
function handlePosition(pos){const lat=pos.coords.latitude,lng=pos.coords.longitude,acc=pos.coords.accuracy;let gps=loadGps();const current={lat,lng};if(acc&&acc>GPS_MAX_ACCURACY_M){saveGps({...gps,enabled:true,status:'low-accuracy',lat,lng,accuracy:acc,lastMove:0,dir:'오차큼'});renderHud();return}if(!gps.origin){const p=player();gps={...gps,enabled:true,status:'on',origin:current,last:current,baseWorld:{x:Number(p.x||0),y:Number(p.y||0)},lat,lng,accuracy:acc,lastMove:0,totalMove:Number(gps.totalMove||0),dir:'기준점',chasing:false};saveGps(gps);document.body.dataset.gps='on';renderHud();toast('탐험모드 기준점 등록 완료');return}
const last=gps.last||gps.origin;const moved=metersBetween(last,current);const raw=deltaMeters(last,current);const dir=dirLabel(raw.east,raw.north);gps={...gps,enabled:true,status:'on',lat,lng,accuracy:acc,lastMove:moved,dir:dir.txt};if(moved<GPS_MIN_MOVE_M){saveGps(gps);document.body.dataset.gps='on';renderHud();return}
const totalRaw=deltaMeters(gps.origin,current);const rotated=rotateByHeading(totalRaw.east,totalRaw.north);const base=gps.baseWorld||{x:0,y:0};const target={x:Math.max(-2200,Math.min(2200,base.x+rotated.east*GPS_WORLD_SCALE)),y:Math.max(-2200,Math.min(2200,base.y-rotated.north*GPS_WORLD_SCALE))};gps.last=current;gps.world=target;gps.totalMove=Number(gps.totalMove||0)+moved;gps.chasing=true;saveGps(gps);document.body.dataset.gps='on';chaseTarget(target,`GPS 이동 ${dir.txt} ${moved.toFixed(1)}m`);pulse();renderHud();toast(`📍 ${dir.txt} ${moved.toFixed(1)}m 이동 감지`)}
async function startCompass(){if(window.CATCHABUGS_RADAR_COMPASS?.on)return window.CATCHABUGS_RADAR_COMPASS.on();const btn=$('#radarCompassToggle');if(btn&&!btn.textContent.includes('OFF'))btn.click()}
function start(){if(!isMobile()){setEnabled(false);toast('탐험모드는 모바일에서만 사용할 수 있습니다.');return false}if(!navigator.geolocation){setEnabled(false);toast('이 브라우저는 GPS를 지원하지 않습니다.');return false}setEnabled(true);startCompass();const old=loadGps();saveGps({...old,enabled:true,status:'requesting'});document.body.dataset.gps='requesting';renderHud();navigator.geolocation.getCurrentPosition(handlePosition,(err)=>{saveGps({...loadGps(),enabled:false,status:'denied',error:err.message});setEnabled(false);renderHud();toast('GPS 권한이 거부되었거나 사용할 수 없습니다.')},{enableHighAccuracy:true,timeout:8000,maximumAge:5000});if(watchId===null){watchId=navigator.geolocation.watchPosition(handlePosition,(err)=>{saveGps({...loadGps(),status:'error',error:err.message});renderHud()},{enableHighAccuracy:true,timeout:12000,maximumAge:5000})}toast('탐험모드 권한 요청 중');return true}
function stop(){if(watchId!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId);watchId=null}if(anim)cancelAnimationFrame(anim);anim=null;setEnabled(false);saveGps({...loadGps(),enabled:false,status:'off',chasing:false});document.body.dataset.gps='off';$('#gpsHud')?.remove();toast('탐험모드 OFF')}
function toggle(){const settings=loadSettings();if(settings.gpsEnabled)stop();else start()}
function sync(){const settings=loadSettings();if(settings.gpsEnabled&&watchId===null)start();if(!settings.gpsEnabled&&watchId!==null)stop();renderHud()}
function label(){const gps=loadGps();if(!isMobile())return '모바일 전용';if(loadSettings().gpsEnabled)return gps.status==='on'?`ON · ${gps.accuracy?Math.round(gps.accuracy)+'m':'측정중'} · ${gps.dir||'-'}`:gps.status==='low-accuracy'?'정확도 낮음':'권한 확인 중';return '현재 OFF'}
window.CATCHABUGS_GPS={start,stop,toggle,isMobile,label,loadGps};
document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,900));setTimeout(sync,1600);
